"""Metric contracts catalog (machine-readable core)."""

from __future__ import annotations

from typing import Any, Dict, List

from . import DAILY_FAST_LE_6S_MS, STUDY_FAST_LT_4S_MS


def catalog_v2() -> List[Dict[str, Any]]:
    """Formal contracts for Daily V2 metrics."""
    rows: List[Dict[str, Any]] = []

    def add(**kw):
        rows.append(kw)

    add(
        metric_id="live_ok_count",
        display_name="LIVE_OK count",
        description="Distinct LIVE_OK Back H3BUP orders in cohort by order_id",
        metric_version="v2.0",
        universe="LIVE_OK",
        primary_timestamp="created_at",
        time_window="execution_day_utc half-open",
        source="executor_live.jsonl",
        join_key="order_id",
        filters="status=LIVE_OK; exec_side=back; policy_version contains H3BUP_vNext; exclude heartbeat",
        numerator="n distinct order_id",
        denominator="n/a",
        formula="count(distinct order_id)",
        unit="count",
        null_policy="MISSING if source failed; 0 only if healthy empty cohort",
        dedup_rule="keep latest created_at per order_id",
        freshness_requirement="executor jsonl mtime within report freshness gate",
        minimum_coverage=None,
        minimum_n=0,
        statistical_status_rule="AVAILABLE if source HEALTHY",
        owner_module="ops.daily_v2.universes",
        tests="test_live_ok_dedup;test_heartbeat_excluded;test_policy_filter",
    )
    add(
        metric_id="roi_settled",
        display_name="ROI settled",
        description="Settled P&L over settled stake; open excluded from denominator",
        metric_version="v2.0",
        universe="SETTLED_ORDER",
        primary_timestamp="created_at",
        time_window="execution_day_utc cohort; settlement as_of report_cutoff",
        source="executor_live.jsonl + accounting balance by order_id",
        join_key="order_id",
        filters="LIVE_OK cohort ∩ settled accounting; exclude open; void/push pnl=0 stake included",
        numerator="sum(pnl_confirmed_settled)",
        denominator="sum(stake_confirmed_settled)",
        formula="sum(pnl)/sum(stake)",
        unit="fraction",
        null_policy="UNAVAILABLE_STALE if accounting STALE; MISSING if join fails; INSUFFICIENT_N if n<min",
        dedup_rule="one accounting pnl per order_id (lifetime sum P&L-like)",
        freshness_requirement="accounting health HEALTHY",
        minimum_coverage=0.95,
        minimum_n=1,
        statistical_status_rule="INSUFFICIENT_N if n_settled < 30 for inference; AVAILABLE for descriptive",
        owner_module="ops.daily_v2.performance",
        tests="test_open_not_in_roi_settled;test_void_push;test_missing_accounting",
    )
    add(
        metric_id="roiw_total_v1",
        display_name="ROIw Total (legacy v1)",
        description="Legacy Daily V1: sum(pnl_ledger)/sum(exposure_exec)*100 for Back LIVE_OK on created_at day; includes open if present in ledger",
        metric_version="v1.0",
        universe="LIVE_OK",
        primary_timestamp="created_at",
        time_window="execution_day_utc",
        source="executor_live.jsonl + balance.csv",
        join_key="order_id",
        filters="Back LIVE_OK; pnl-like ledger rows; deposits/withdrawals excluded",
        numerator="sum(pnl)",
        denominator="sum(exposure/stake)",
        formula="(sum pnl / sum exposure) * 100",
        unit="percent",
        null_policy="None/— if den=0; missing oid excluded from num/den",
        dedup_rule="latest LIVE_OK per order_id",
        freshness_requirement="accounting CSV present",
        minimum_coverage=None,
        minimum_n=0,
        statistical_status_rule="AVAILABLE descriptive; complementary to roi_settled",
        owner_module="ops.daily_v2.performance",
        tests="test_roiw_total_contract",
    )
    add(
        metric_id="roiw_total_v2",
        display_name="ROIw Total v2 (settled-aware)",
        description="Same formula as v1 but reports open/settled/void/missing splits; principal performance metric remains roi_settled",
        metric_version="v2.0",
        universe="LIVE_OK",
        primary_timestamp="created_at",
        time_window="execution_day_utc",
        source="executor_live.jsonl + balance.csv + open_stakes.csv",
        join_key="order_id",
        filters="Back LIVE_OK H3BUP",
        numerator="sum(pnl settled)",
        denominator="sum(stake settled)",
        formula="(sum pnl_settled / sum stake_settled) * 100 when settled; else status PARTIAL",
        unit="percent",
        null_policy="PARTIAL if open remain; MISSING if no accounting",
        dedup_rule="order_id",
        freshness_requirement="accounting HEALTHY",
        minimum_coverage=None,
        minimum_n=0,
        statistical_status_rule="complementary",
        owner_module="ops.daily_v2.performance",
        tests="test_roiw_v1_v2_side_by_side",
    )
    add(
        metric_id="daily_fast_le_6s",
        display_name="DAILY_FAST_LE_6S",
        description="pre_submit_ms <= 6000; Daily primary fast bucket",
        metric_version="v2.0",
        universe="LIVE_OK",
        primary_timestamp="created_at",
        time_window="execution_day_utc",
        source="executor_live.jsonl validation_summary.pre_submit_ms",
        join_key="order_id",
        filters=f"pre_submit_ms <= {DAILY_FAST_LE_6S_MS}; missing => not classified as slow or fast",
        numerator="n fast",
        denominator="n with pre_submit_ms present",
        formula="pre_submit_ms <= 6000",
        unit="count/rate",
        null_policy="MISSING pre_submit_ms => separate NA bucket; never coerce to slow",
        dedup_rule="order_id",
        freshness_requirement=None,
        minimum_coverage=None,
        minimum_n=0,
        statistical_status_rule="AVAILABLE",
        owner_module="ops.daily_v2.latency_buckets",
        tests="test_daily_fast_le_6s;test_4s_boundary",
    )
    add(
        metric_id="study_fast_lt_4s",
        display_name="STUDY_FAST_LT_4S",
        description="Exploratory study bucket pre_submit_ms < 4000; never replaces Daily fast",
        metric_version="v2.0",
        universe="LIVE_OK",
        primary_timestamp="created_at",
        time_window="execution_day_utc",
        source="executor_live.jsonl",
        join_key="order_id",
        filters=f"pre_submit_ms < {STUDY_FAST_LT_4S_MS}",
        numerator="n",
        denominator="n with pre_submit_ms",
        formula="pre_submit_ms < 4000",
        unit="count/rate",
        null_policy="MISSING separate",
        dedup_rule="order_id",
        freshness_requirement=None,
        minimum_coverage=None,
        minimum_n=0,
        statistical_status_rule="exploratory label required",
        owner_module="ops.daily_v2.latency_buckets",
        tests="test_study_fast_lt_4s;test_4s_boundary",
    )
    add(
        metric_id="clv_post_5m_strict",
        display_name="CLV POST_5M strict",
        description="Forward CLV strict valid for POST_5M window after activation",
        metric_version="v2.0",
        universe="CLV_VALID_STRICT",
        primary_timestamp="live_ok_ts",
        time_window="post CLV activation only",
        source="h3bup_clv obligations+snapshots",
        join_key="order_id+window",
        filters="forward-only; same event/market/period/side/line; before kickoff for closing",
        numerator="mean/median clv when AVAILABLE",
        denominator="obligations due",
        formula="(entry-closing)/closing",
        unit="fraction",
        null_policy="INSUFFICIENT_N / NOT_DUE / MISSING — never 0 by default",
        dedup_rule="obligation_id",
        freshness_requirement="CLV worker health",
        minimum_coverage=None,
        minimum_n=30,
        statistical_status_rule="INSUFFICIENT_N if n<30",
        owner_module="ops.daily_v2.clv",
        tests="test_clv_windows_separated;test_pre_activation_excluded",
    )
    add(
        metric_id="fair_edge",
        display_name="Fair edge",
        description="Fair edge / de-vig not implemented in Phase 2R",
        metric_version="v2.0",
        universe="NOT_APPLICABLE",
        primary_timestamp="n/a",
        time_window="n/a",
        source="n/a",
        join_key="n/a",
        filters="n/a",
        numerator=None,
        denominator=None,
        formula="NOT_IMPLEMENTED",
        unit=None,
        null_policy="value=null status=NOT_IMPLEMENTED (never 0)",
        dedup_rule="n/a",
        freshness_requirement=None,
        minimum_coverage=None,
        minimum_n=None,
        statistical_status_rule="NOT_IMPLEMENTED",
        owner_module="ops.daily_v2.canonical",
        tests="test_fair_edge_not_implemented",
    )
    add(
        metric_id="e2e_ws_to_live_ok",
        display_name="E2E WS→LIVE_OK",
        description="End-to-end latency from WS detect to LIVE_OK via h3bup_e2e_trace",
        metric_version="v2.0",
        universe="E2E_TRACE",
        primary_timestamp="event_ts",
        time_window="report window / rolling diagnostic",
        source="h3bup_e2e_trace.jsonl",
        join_key="trace_id",
        filters="schema_version=1; dedupe trace_id; status LIVE_OK subset for this metric",
        numerator="median/p95 ms",
        denominator="n traces with both endpoints",
        formula="live_ok_ts - ws_ts",
        unit="ms",
        null_policy="INSUFFICIENT_N if n=0; never compute percentiles on empty",
        dedup_rule="trace_id",
        freshness_requirement="E2E enabled",
        minimum_coverage=None,
        minimum_n=1,
        statistical_status_rule="INSUFFICIENT_N if n=0",
        owner_module="ops.daily_v2.e2e",
        tests="test_e2e_n0;test_trace_dedup;test_jsonl_rotation",
    )
    return rows


def catalog_to_csv_rows() -> List[Dict[str, Any]]:
    return catalog_v2()
